sudo: required

services:
  - docker

env:
  - DOCKER_PYTHON="3.4"
  - DOCKER_PYTHON="3.5"

language: python

before_install:
  - cat Dockerfile | sed "s/{{python_version}}/$DOCKER_PYTHON/" | docker build -t etataurov/asyncio_apns -

script:
  - docker run etataurov/asyncio_apns py.test -v
