sudo: required
dist: trusty
language: python
python:
    - "3.4"
    - "3.5"
install:
    - "pip install -r requirements-test.txt"
    - "pip install python-coveralls"
    - "pip install flake8"
    - "pip install -e ."
script:
    - "flake8 asyncio_apns"
    - "py.test -v --cov=asyncio_apns"
after_success:
    - "coveralls"
