sudo: required

services:
  - docker

env:
  - DOCKER_PYTHON="3.5"

language: python

before_install:
  - add-apt-repository ppa:ubuntu-lxc/lxd-stable
  - apt-get update
  - apt-get install golang

install:
  - pushd tests_mocked_server && go build go-apns-server.go && popd
  - sed "s/{{python_version}}/$DOCKER_PYTHON/" Dockerfile.template > Dockerfile
  - docker build -t etataurov/asyncio_apns .
  - pip install python-coveralls
  - mkdir -p output

script:
  - docker run --rm etataurov/asyncio_apns flake8 asyncio_apns
  - docker run --rm -v $(pwd)/output:/app/output etataurov/asyncio_apns /bin/sh -c "py.test tests tests_mocked_server -v --cov=asyncio_apns && cp .coverage output/"

after_success:
  -  docker run --rm -e "TRAVIS_JOB_ID=$TRAVIS_JOB_ID" -e "TRAVIS_BRANCH=$TRAVIS_BRANCH" -v $(pwd)/output:/app/output etataurov/asyncio_apns /bin/sh -c "coveralls -d output/.coverage"
