sudo: required

services:
  - docker
language: python

before_install:
  - docker build -t etataurov/asyncio_apns .

script:
  - docker run etataurov/asyncio_apns py.test -v tests tests_mocked_server
