sudo: required

services:
  - docker

env:
  - DOCKER_PYTHON="3.5"
  - DOCKER_PYTHON="3.6"

language: python

before_install:
  - sed "s/{{python_version}}/$DOCKER_PYTHON/" Dockerfile.template > Dockerfile
  - docker build -t etataurov/asyncio_apns .

script:
  - docker run etataurov/asyncio_apns py.test -v
